import type { DemoScenario, ReferenceStatus, ScenarioInput } from "./types";

export const demoInput: ScenarioInput = {
  quote_name: "Hamburg profil teklifi",
  product_name: "Sıcak haddelenmiş I profil",
  destination: "Almanya",
  origin_country: "Türkiye",
  cn_code: "72163211",
  import_period: "2026-Q2",
  emissions_mode: "default",
  quote_value_eur: 128460,
  production_cost_eur: 101780,
  shipment_tonnes: 84.6,
  verified_emissions_intensity: null,
  verified_sefa_intensity: null,
  try_cost_exposure_rate: 0.62,
  fx_volatility_mode: "official",
  fx_volatility_rate: 0.055,
  delivery_horizon_days: 60,
  input_cost_volatility_rate: 0.038,
  target_margin_rate: 0.12,
  simulations: 2500,
  seed: 42,
};
export const demoFallback: DemoScenario = {
  input: demoInput,
  result: {
    scenario_id: "offline-preview",
    generated_at: "2026-09-30T00:00:00Z",
    model_status: "decision_support",
    expected_margin_eur: 20547.73,
    expected_margin_rate: 0.15995,
    downside_margin_eur: 15146.49,
    negative_margin_probability: 0,
    cbam_cost_eur: 6243.45,
    safe_floor_price_eur: 128765.35,
    recommended_buffer_eur: 305.35,
    cbam: {
      method: "default",
      catalog_version: "2026-08-10",
      origin_country: "Türkiye",
      cn_code: "72163211",
      import_period: "2026-Q2",
      shipment_tonnes: 84.6,
      embedded_emissions_intensity: 2.31,
      benchmark_intensity: 1.364,
      cbam_factor: 0.975,
      cscf: 1,
      cscf_status: "preliminary",
      sefa_intensity: 1.3299,
      gross_embedded_emissions_tco2e: 195.426,
      free_allocation_adjustment_tco2e: 112.50954,
      certificates_required: 82.91646,
      certificate_price_eur: 75.28,
      estimated_cost_eur: 6241.95,
      threshold_signal: "shipment_alone_above",
      threshold_note:
        "50 ton eşiği tek teklife değil, AB ithalatçısının dört sektördeki yıllık toplam ithalatına uygulanır.",
      selection: {
        matched_default_cn_code: "7216",
        matched_benchmark_cn_code: "72163211",
        production_route: "(C)",
        benchmark_column: "B",
        benchmark_description:
          "Paralel başlıklı, sıcak haddelenmiş demir veya alaşımsız çelik I profil",
      },
      source_ids: [
        "eu-benchmarks-2026-02-13",
        "eu-cbam-prices-2026",
        "eu-default-values-2026-08-10",
        "eu-free-allocation-guidance-2026-08-14",
      ],
      warnings: [
        "2026 sektörler arası düzeltme faktörü, son Komisyon rehberinde ön değer olarak yayımlanmıştır.",
      ],
      trace: [
        {
          key: "embedded_emissions",
          label: "Gömülü emisyon",
          formula: "İthalat miktarı × resmi varsayılan emisyon yoğunluğu",
          expression: "84,6 × 2,310",
          unit: "tCO2e",
          source_ids: ["eu-default-values-2026-08-10"],
        },
        {
          key: "sefa",
          label: "Spesifik serbest tahsis düzeltmesi",
          formula: "CBAM faktörü × CSCF × Column B benchmark",
          expression: "0,975 × 1,000 × 1,364",
          unit: "tCO2e/t",
          source_ids: [
            "eu-benchmarks-2026-02-13",
            "eu-free-allocation-guidance-2026-08-14",
          ],
        },
        {
          key: "free_allocation_adjustment",
          label: "Serbest tahsis düzeltmesi",
          formula: "İthalat miktarı × SEFA",
          expression: "84,6 × 1,3299",
          unit: "tCO2e",
          source_ids: ["eu-benchmarks-2026-02-13"],
        },
        {
          key: "certificates",
          label: "Tahmini sertifika yükümlülüğü",
          formula: "max(0, gömülü emisyon - serbest tahsis düzeltmesi)",
          expression: "max(0, 195,426 - 112,50954)",
          unit: "sertifika",
          source_ids: ["eu-free-allocation-guidance-2026-08-14"],
        },
        {
          key: "cbam_cost",
          label: "Tahmini CBAM maliyeti",
          formula: "Sertifika yükümlülüğü × dönem sertifika fiyatı",
          expression: "82,91646 × 75,28",
          unit: "EUR",
          source_ids: ["eu-cbam-prices-2026"],
        },
      ],
    },
    fx: {
      mode: "official",
      source_id: "tcmb-eur-try",
      source_title: "TCMB Gösterge Niteliğindeki Döviz Kurları",
      source_url: "https://www.tcmb.gov.tr/kurlar/kurlar_tr.html",
      catalog_version: "2026-09-30",
      latest_observation_date: "2026-09-30",
      latest_eur_try_mid: 55.60675,
      observation_count: 371,
      delivery_horizon_days: 60,
      horizon_business_days: 41,
      ewma_decay: 0.94,
      daily_volatility_rate: 0.002432,
      annualized_volatility_rate: 0.038611,
      raw_horizon_volatility_rate: 0.015574,
      calibration_multiplier: 1.326782,
      model_volatility_rate: 0.020663,
      applied_volatility_rate: 0.020663,
      recent_20_business_day_change_rate: -0.004233,
      backtest: {
        forecast_count: 225,
        calibration_count: 158,
        holdout_count: 67,
        lookback_business_days: 126,
        horizon_business_days: 20,
        calibration_multiplier: 1.326782,
        raw_coverage_80_rate: 0.53731,
        raw_coverage_95_rate: 0.83582,
        calibrated_coverage_80_rate: 0.73134,
        calibrated_coverage_95_rate: 0.92537,
        mean_absolute_actual_return_rate: 0.016876,
        mean_raw_forecast_volatility_rate: 0.014817,
      },
    },
    percentiles: [
      { percentile: 10, margin_eur: 15146.49, margin_rate: 0.11791 },
      { percentile: 25, margin_eur: 17810.86, margin_rate: 0.13865 },
      { percentile: 50, margin_eur: 20595.59, margin_rate: 0.16033 },
      { percentile: 75, margin_eur: 23434.94, margin_rate: 0.18243 },
      { percentile: 90, margin_eur: 25836.05, margin_rate: 0.20112 },
    ],
    histogram: [
      { start_eur: 4333.51, end_eur: 6587.76, count: 3 },
      { start_eur: 6587.76, end_eur: 8842.02, count: 9 },
      { start_eur: 8842.02, end_eur: 11096.27, count: 24 },
      { start_eur: 11096.27, end_eur: 13350.52, count: 66 },
      { start_eur: 13350.52, end_eur: 15604.78, count: 190 },
      { start_eur: 15604.78, end_eur: 17859.03, count: 340 },
      { start_eur: 17859.03, end_eur: 20113.28, count: 494 },
      { start_eur: 20113.28, end_eur: 22367.54, count: 536 },
      { start_eur: 22367.54, end_eur: 24621.79, count: 434 },
      { start_eur: 24621.79, end_eur: 26876.04, count: 248 },
      { start_eur: 26876.04, end_eur: 29130.3, count: 112 },
      { start_eur: 29130.3, end_eur: 31384.55, count: 35 },
      { start_eur: 31384.55, end_eur: 33638.8, count: 6 },
      { start_eur: 33638.8, end_eur: 35893.06, count: 3 },
    ],
    contributions: [
      {
        key: "production",
        label: "Üretim maliyeti",
        amount_eur: 101780,
        share_rate: 0.89734,
      },
      {
        key: "cbam",
        label: "CBAM sertifika etkisi",
        amount_eur: 6243.45,
        share_rate: 0.05504,
      },
      {
        key: "risk_buffer",
        label: "Belirsizlik tamponu",
        amount_eur: 5401.24,
        share_rate: 0.04762,
      },
    ],
    assumptions: [
      "CBAM tabanı, seçilen dönem için yayımlanmış resmi sertifika fiyatını kullanır.",
      "Resmi varsayılan modunda Türkiye emisyon değeri ve Column B benchmark eşleştirilir.",
      "Kur şoku, TCMB EUR/TRY serisinden kalibre edilen lognormal dağılımla örneklenir.",
      "Girdi maliyeti şokları normal dağılımla örneklenir.",
      "Karbon fiyatı oynaklığı teklif riski için yüzde 12 kabul edilir.",
      "Sonuç karar desteğidir; resmi beyan veya hukuki görüş değildir.",
    ],
  },
};
export const demoReferenceStatus: ReferenceStatus = {
  mode: "official_snapshot",
  catalog_version: "2026-08-10",
  latest_certificate_period: "2026-Q2",
  latest_certificate_price_eur: 75.28,
  default_value_count: 250,
  benchmark_count: 1804,
  sources: [
    {
      id: "eu-default-values-2026-08-10",
      title: "Düzeltilmiş kesin dönem varsayılan değerleri",
      publisher: "European Commission, DG TAXUD",
      published_on: "2026-08-10",
      legal_basis: "Uygulama Tüzüğü (AB) 2026/1740 ve 2025/2621",
      url: "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/cbam-legislation-and-guidance_en",
      binding: false,
    },
    {
      id: "eu-benchmarks-2026-02-13",
      title: "Kesin dönem benchmark tablosu",
      publisher: "European Commission, DG TAXUD",
      published_on: "2026-02-13",
      legal_basis: "Uygulama Tüzüğü (AB) 2025/2620",
      url: "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/cbam-legislation-and-guidance_en",
      binding: false,
    },
    {
      id: "eu-cbam-prices-2026",
      title: "CBAM sertifika fiyatları",
      publisher: "European Commission, DG TAXUD",
      published_on: "2026-07-06",
      legal_basis: "Uygulama Tüzüğü (AB) 2025/2548",
      url: "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/price-cbam-certificates_en",
      binding: true,
    },
    {
      id: "eu-free-allocation-guidance-2026-08-14",
      title: "Serbest tahsis düzeltmesi rehberi",
      publisher: "European Commission, DG TAXUD",
      published_on: "2026-08-14",
      legal_basis: "Uygulama Tüzüğü (AB) 2025/2620 açıklayıcı rehberi",
      url: "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/cbam-legislation-and-guidance_en",
      binding: false,
    },
  ],
  notes: [
    "Excel dosyaları bilgi amaçlıdır; bağlayıcı metinler atıf yapılan AB düzenlemeleridir.",
    "2026 CSCF değeri 14 Ağustos 2026 rehberinde ön değer olarak işaretlenmiştir.",
  ],
};
