import type { DemoScenario, ReferenceStatus, ScenarioInput } from "./types";

export const demoInput: ScenarioInput = {
  quote_name: "Hamburg profil teklifi",
  product_name: "Sıcak haddelenmiş I profil",
  destination: "Almanya",
  origin_country: "Türkiye",
  cn_code: "72163211",
  import_period: "2026-Q2",
  emissions_mode: "default",
  quote_value_eur: 128460,
  production_cost_eur: 101780,
  shipment_tonnes: 84.6,
  verified_emissions_intensity: null,
  verified_sefa_intensity: null,
  try_cost_exposure_rate: 0.62,
  fx_volatility_rate: 0.055,
  input_cost_volatility_rate: 0.038,
  target_margin_rate: 0.12,
  simulations: 2500,
  seed: 42,
};
export const demoFallback: DemoScenario = {
  input: demoInput,
  result: {
    scenario_id: "offline-preview",
    generated_at: "2026-09-30T00:00:00Z",
    model_status: "decision_support",
    expected_margin_eur: 20582.65,
    expected_margin_rate: 0.16023,
    downside_margin_eur: 13720.68,
    negative_margin_probability: 0,
    cbam_cost_eur: 6243.45,
    safe_floor_price_eur: 130385.59,
    recommended_buffer_eur: 1925.59,
    cbam: {
      method: "default",
      catalog_version: "2026-08-10",
      origin_country: "Türkiye",
      cn_code: "72163211",
      import_period: "2026-Q2",
      shipment_tonnes: 84.6,
      embedded_emissions_intensity: 2.31,
      benchmark_intensity: 1.364,
      cbam_factor: 0.975,
      cscf: 1,
      cscf_status: "preliminary",
      sefa_intensity: 1.3299,
      gross_embedded_emissions_tco2e: 195.426,
      free_allocation_adjustment_tco2e: 112.50954,
      certificates_required: 82.91646,
      certificate_price_eur: 75.28,
      estimated_cost_eur: 6241.95,
      threshold_signal: "shipment_alone_above",
      threshold_note:
        "50 ton eşiği tek teklife değil, AB ithalatçısının dört sektördeki yıllık toplam ithalatına uygulanır.",
      selection: {
        matched_default_cn_code: "7216",
        matched_benchmark_cn_code: "72163211",
        production_route: "(C)",
        benchmark_column: "B",
        benchmark_description:
          "Paralel başlıklı, sıcak haddelenmiş demir veya alaşımsız çelik I profil",
      },
      source_ids: [
        "eu-benchmarks-2026-02-13",
        "eu-cbam-prices-2026",
        "eu-default-values-2026-08-10",
        "eu-free-allocation-guidance-2026-08-14",
      ],
      warnings: [
        "2026 sektörler arası düzeltme faktörü, son Komisyon rehberinde ön değer olarak yayımlanmıştır.",
      ],
      trace: [
        {
          key: "embedded_emissions",
          label: "Gömülü emisyon",
          formula: "İthalat miktarı × resmi varsayılan emisyon yoğunluğu",
          expression: "84,6 × 2,310",
          unit: "tCO2e",
          source_ids: ["eu-default-values-2026-08-10"],
        },
        {
          key: "sefa",
          label: "Spesifik serbest tahsis düzeltmesi",
          formula: "CBAM faktörü × CSCF × Column B benchmark",
          expression: "0,975 × 1,000 × 1,364",
          unit: "tCO2e/t",
          source_ids: [
            "eu-benchmarks-2026-02-13",
            "eu-free-allocation-guidance-2026-08-14",
          ],
        },
        {
          key: "free_allocation_adjustment",
          label: "Serbest tahsis düzeltmesi",
          formula: "İthalat miktarı × SEFA",
          expression: "84,6 × 1,3299",
          unit: "tCO2e",
          source_ids: ["eu-benchmarks-2026-02-13"],
        },
        {
          key: "certificates",
          label: "Tahmini sertifika yükümlülüğü",
          formula: "max(0, gömülü emisyon - serbest tahsis düzeltmesi)",
          expression: "max(0, 195,426 - 112,50954)",
          unit: "sertifika",
          source_ids: ["eu-free-allocation-guidance-2026-08-14"],
        },
        {
          key: "cbam_cost",
          label: "Tahmini CBAM maliyeti",
          formula: "Sertifika yükümlülüğü × dönem sertifika fiyatı",
          expression: "82,91646 × 75,28",
          unit: "EUR",
          source_ids: ["eu-cbam-prices-2026"],
        },
      ],
    },
    percentiles: [
      { percentile: 10, margin_eur: 13720.68, margin_rate: 0.10681 },
      { percentile: 25, margin_eur: 16972.35, margin_rate: 0.13212 },
      { percentile: 50, margin_eur: 20618.14, margin_rate: 0.1605 },
      { percentile: 75, margin_eur: 24198.99, margin_rate: 0.18838 },
      { percentile: 90, margin_eur: 27260.63, margin_rate: 0.21221 },
    ],
    histogram: [
      { start_eur: 307.73, end_eur: 3171.58, count: 3 },
      { start_eur: 3171.58, end_eur: 6035.44, count: 13 },
      { start_eur: 6035.44, end_eur: 8899.3, count: 22 },
      { start_eur: 8899.3, end_eur: 11763.16, count: 74 },
      { start_eur: 11763.16, end_eur: 14627.02, count: 222 },
      { start_eur: 14627.02, end_eur: 17490.88, count: 369 },
      { start_eur: 17490.88, end_eur: 20354.74, count: 494 },
      { start_eur: 20354.74, end_eur: 23218.59, count: 520 },
      { start_eur: 23218.59, end_eur: 26082.45, count: 409 },
      { start_eur: 26082.45, end_eur: 28946.31, count: 237 },
      { start_eur: 28946.31, end_eur: 31810.17, count: 94 },
      { start_eur: 31810.17, end_eur: 34674.03, count: 37 },
      { start_eur: 34674.03, end_eur: 37537.89, count: 3 },
      { start_eur: 37537.89, end_eur: 40401.75, count: 3 },
    ],
    contributions: [
      {
        key: "production",
        label: "Üretim maliyeti",
        amount_eur: 101780,
        share_rate: 0.88593,
      },
      {
        key: "cbam",
        label: "CBAM sertifika etkisi",
        amount_eur: 6243.45,
        share_rate: 0.05435,
      },
      {
        key: "risk_buffer",
        label: "Belirsizlik tamponu",
        amount_eur: 6861.97,
        share_rate: 0.05973,
      },
    ],
    assumptions: [
      "CBAM tabanı, seçilen dönem için yayımlanmış resmi sertifika fiyatını kullanır.",
      "Resmi varsayılan modunda Türkiye emisyon değeri ve Column B benchmark eşleştirilir.",
      "Kur ve girdi maliyeti şokları normal dağılımla örneklenir.",
      "Karbon fiyatı oynaklığı teklif riski için yüzde 12 kabul edilir.",
      "Sonuç karar desteğidir; resmi beyan veya hukuki görüş değildir.",
    ],
  },
};
export const demoReferenceStatus: ReferenceStatus = {
  mode: "official_snapshot",
  catalog_version: "2026-08-10",
  latest_certificate_period: "2026-Q2",
  latest_certificate_price_eur: 75.28,
  default_value_count: 250,
  benchmark_count: 1804,
  sources: [
    {
      id: "eu-default-values-2026-08-10",
      title: "Düzeltilmiş kesin dönem varsayılan değerleri",
      publisher: "European Commission, DG TAXUD",
      published_on: "2026-08-10",
      legal_basis: "Uygulama Tüzüğü (AB) 2026/1740 ve 2025/2621",
      url: "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/cbam-legislation-and-guidance_en",
      binding: false,
    },
    {
      id: "eu-benchmarks-2026-02-13",
      title: "Kesin dönem benchmark tablosu",
      publisher: "European Commission, DG TAXUD",
      published_on: "2026-02-13",
      legal_basis: "Uygulama Tüzüğü (AB) 2025/2620",
      url: "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/cbam-legislation-and-guidance_en",
      binding: false,
    },
    {
      id: "eu-cbam-prices-2026",
      title: "CBAM sertifika fiyatları",
      publisher: "European Commission, DG TAXUD",
      published_on: "2026-07-06",
      legal_basis: "Uygulama Tüzüğü (AB) 2025/2548",
      url: "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/price-cbam-certificates_en",
      binding: true,
    },
    {
      id: "eu-free-allocation-guidance-2026-08-14",
      title: "Serbest tahsis düzeltmesi rehberi",
      publisher: "European Commission, DG TAXUD",
      published_on: "2026-08-14",
      legal_basis: "Uygulama Tüzüğü (AB) 2025/2620 açıklayıcı rehberi",
      url: "https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism/cbam-legislation-and-guidance_en",
      binding: false,
    },
  ],
  notes: [
    "Excel dosyaları bilgi amaçlıdır; bağlayıcı metinler atıf yapılan AB düzenlemeleridir.",
    "2026 CSCF değeri 14 Ağustos 2026 rehberinde ön değer olarak işaretlenmiştir.",
  ],
};
